---
title: "R Notebook"
output: html_notebook
---

Wykorystujemy pakiet stringr (stringi) do wyrażeń regularnych

```{r}
library(stringr)
```

```{r}
tekst <- "Mieszkanie ma powierzchnię 20,25 m2 a cena wynosi 200000. Inne mieszkanie ma powierzchnię 100.28 m2 a cena wynosi 1 mln zł."
```

Weryfikujemy czy w tekście znajduje się określony wzorzec.

```{r}
str_detect(string = tekst,
           pattern = "\\d{1,3}(\\.|\\,)\\d{1,2}")
```

Wyciągamy elementy spełniające wzorzec z tekstu

```{r}
str_extract(string = tekst,
            pattern = "\\d{1,3}(\\.|\\,)\\d{1,2}")
```

```{r}
str_extract_all(string = c(tekst,tekst),
                pattern = "\\d{1,3}(\\.|\\,)\\d{1,2}", 
                simplify = FALSE)
```

```{r}
str_extract_all(string = c(tekst,tekst),
                pattern = "\\d{1,3}(\\.|\\,)\\d{1,2}", 
                simplify = TRUE)
```

Zamieniamy wzorzec na określony tekst

```{r}
str_replace(string = tekst,
            pattern = "\\d{1,3}(\\.|\\,)\\d{1,2}", 
            replacement = "XXX")
```

```{r}
str_count(string = tekst,
          pattern = "\\d{1,3}(\\.|\\,)\\d{1,2}")
```

```{r}
zadanie <- "Mieszkanie ma powierzchnię 20,25 m2 a cena wynosi 200000 PLN.
Inne mieszkanie ma powierzchnię 100.28 m2 a cena wynosi 1 mln zł.
Nowa nieruchomość ma 54 m2. Cena wynosi 240 500 zł.
"
```


```{r}
str_extract_all(zadanie, "\\d{1,}((\\s)\\d{1,})?\\s(zł|PLN)")
```

```{r}
library(RVerbalExpressions)
```

```{r}
range(value = c(0,9)) %>%
  one_or_more() %>%
  maybe(" ") 
```

